spring:
  data:
    mongodb:
      uri: mongodb+srv://<username>:<password>@cluster0.un0kaso.mongodb.net/?retryWrites=true&w=majority
      database: MovieBooking
      auto-index-creation: true
server:
  port: 8080
  servlet:
    context-path: /movie-booking-app
