spring:
  data:
    mongodb:
      uri: mongodb+srv://user:user@cluster0.un0kaso.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: MovieBooking
      auto-index-creation: true
server:
  port: 8080
  servlet:
    context-path: /movie-booking-app